name: CI-ubuntu

on: [push, pull_request]

jobs:
  run:
    runs-on: ubuntu-latest

    env:
      OS: ubuntu
      PYTHON: '3.12'
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: ‘2’

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install xvfb # install virtual framebuffer
        sudo apt install gir1.2-webkit2-4.1
        sudo apt install git build-essential pkg-config python3-dev python3-venv libgirepository1.0-dev libcairo2-dev gir1.2-gtk-3.0 libcanberra-gtk3-module # install toga dependencies
        python -m pip install --upgrade pip
        python -m pip install -r requirements_ubuntu.txt

    - name: Generate Report
      run: |
        xvfb-run python -m unittest discover -s tests -t . -v
